server:
  port: 0

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      instance:
        prefer-ip-address: true

cloud:
  gateway:
    routes:
      - id: doctor-service
        uri: lb://doctor-service
        predicates:
          - Path=/doctor/**
        filters:
          - RewritePath=/doctor/(?<remaining>.*),/${remaining}
      - id: patient-service
        uri: lb://patient-service
        predicates:
          - Path=/patient/**
        filters:
          - RewritePath=/patient/(?<remaining>.*),/${remaining}

  discovery:
    locator:
      enabled: true
      lower-case-service-id: true